config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'users/index'
  get 'users/show'
  root 'articles#index'
  get 'home' => 'articles#index'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  post 'tags/:id/edit' => 'tags#edit'

  resources :users, only: %i[index show]

  resources :tags

  resources :users do
    member do
      get :following, :followers
    end
    resources :relationships, only: %i[create destroy]
  end

  resources :articles do
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  acts_as_taggable
  belongs_to :user, counter_cache: :article_count
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  def like_user(user)
    likes.find_by(user_id: user)
  end

  # 記事画像の適用
  has_one_attached :article_picture
  mount_uploader :article_picture, ImageUploader

  validates :title, :body, presence: true
  validates :tag_list, length: { maximum: 20 }
  validates :title, length: { maximum: 100 }
  validates :body, length: { maximum: 20_000 }

  scope :sidebar_limit, -> { limit(10) }
  scope :by_dates, -> { order(created_at: :desc) }
  scope :by_comments, -> { order(comment_count: :desc) }
  scope :update_notice, -> { where(update_note: true) }
end

app/controllers/api/articles_controller.rb
# frozen_string_literal: true

class Api::ArticlesController < ApplicationController
  def index
    @articles = Article.page(params[:page]).per(8).order(created_at: :desc)

    respond_to do |format|
      format.html { render :index }
      format.json { render 'index.json.jbuilder' }
    end
  end

  def show
    @article = Article.find(params[:id])
    @like = Like.find_by(user_id: current_user.id, article_id: params[:id])
    @likes = @article.likes.where(article_id: params[:article_id])
    render 'show', formats: 'json', handlers: 'jbuilder'
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  # [devise由来] ログイン済ユーザーにのみアクセスを許可する。
  before_action :authenticate_user!, except: [:index]

  def index
    @articles = Article.page(params[:page]).per(8).order(created_at: :desc)
  end

  def show
    @article = Article.find(params[:id])
    @like = Like.find_by(user_id: current_user.id, article_id: params[:id])
    @likes = @article.likes.where(article_id: params[:article_id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = current_user.articles.new(article_params)
    @article.author = current_user
    if @article.save
      redirect_to @article, notice: '記事を投稿しました！'
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    @article.assign_attributes(article_params)
    if @article.save
      redirect_to @article, notice: '記事内容を更新しました！'
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to controller: 'articles', action: 'index'
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :article_picture, :update_note)
  end
end

app/helpers/api/articles_helper.rb
# frozen_string_literal: true

module Api::ArticlesHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/views/articles/_article_card.html.erb
<div class="card" id="article-card">
  <div class="card-header p-1 border-secondary" id="author">
    <%= link_to article.user do %>
    <div class="d-flex p-0">
      <div class="d-flex mx-1 align-self-center">
        <%= image_tag article.author.image.url, class: 'rounded', :size => '40x40' if article.author.image.url.present? %>
      </div>
      <div class="d-flex flex-column align-self-center">
        <div class="mr-1 font-weight-bold text-left" id="author">
          <%= article.author.username %>
          <%= render 'users/user_card_attribute_badge', user: article.author %>
        </div>
        <div class="text-truncate" id="date"><%= article.created_at.strftime("%m月%d日 %H:%M") %></div>
      </div>
    </div>
    <% end %>
  </div>
  <div class="card-header border-secondary rounded-0 p-1 pl-2" id="title">
    <%= render 'articles/article_card_notice_type_badge', article: article %>
    <%= article.title %>
  </div>
  <div class="card-header p-1 d-flex justify-content-between">
    <%# <%= render 'tags/tags_badges_line', article: article, tags: article.tag_list %> %>
    <div class="d-flex align-self-center">
      <%= render 'articles/article_card_edit_or_delete_btn', article: article %>
    </div>
  </div>
  <div class="card-body">
    <div class="card d-flex m-0 p-0 border-0 justify-content-center">
      <div class="article-picture-field">
        <%= image_tag article.article_picture.url, class: "article-picture" if article.article_picture.url.present? %>
      </div>
    </div>
    <%= markdown(article.body).html_safe %>
  </div>
  <% if user_signed_in? %>
    <div class="card-footer p-1">
      <div id="like-button-<%= article.id %>">
        <%= render 'articles/article_card_like_btn', article: article, like: like %>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_article_card_edit_or_delete_btn.html.erb
<% if user_signed_in? %>
  <div class="d-flex justify-content-between" id="author-option">
    <div>
      <% if current_user.id == article.user_id %>
        <%= link_to "記事の削除", article, method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'float-left mr-3 btn-sm btn-light', id: 'delete-btn' %>
        <%= link_to "記事の編集", [:edit, article], class: 'float-left mr-3 btn-sm btn-light' ,id: 'edit-btn' %>
      <% else %>
        <span class="badge badge-sm badge-secondary align-self-center">記事の投稿者であれば編集ができます。</span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/articles/_article_card_like_btn.html.erb
<% if article.like_user(current_user.id) %>
  <%= button_to article_like_path(article, like), method: :delete, class: "p-1 btn btn-sm btn-warning", id: "like-button", remote: true do %>
    <%= icon('fa', 'thumbs-up') %>(<%= article.like_count %>) いいねを取り消す
  <% end %>
<% else %>
  <%= button_to [article, article.likes.new(article_id: article.id, user_id: current_user.id)], class: "p-1 btn btn-sm btn-warning", id: "like-button", remote: true do %>
    <%= icon('fa', 'thumbs-up') %>(<%= article.like_count %>) 　いいねする　　
  <% end %>
<% end %>

app/views/articles/_article_card_notice_type_badge.html.erb
<% if article.update_note == true %>
  <div class="ml-1 rounded-pill badge badge-sm badge-warning">アプリ更新</div>
<% end %>

app/views/articles/_articles_cards.html.erb
<div class="card-deck mx-auto" id="columns">
    <% articles.each do |article| %>
      <div class="p-0 col-12 col-sm-6 col-md-4 col-lg-4 col-xl-3 justify-content-center" id="article-<%= article.id %>-<%= article.title %>">
        <div class="pr-3 pb-3">
          <%= render 'articles/articles_cards_card', article: article, user_type: user_type, article_type: article_type %>
        </div>
      </div>
    <% end %>
    <div class="container d-flex">
      <div class="mx-auto">
        <%= paginate articles.page(params[:page]).per(8).order(created_at: :desc) %>
      </div>
    </div>
</div>

app/views/articles/_articles_cards_card.html.erb
<div class="m-0 card rounded-0">
  <button type="button" data-toggle="modal" data-target="#user-modal-<%= user_type %>-<%= article.user.id %>" class="m-0 p-0 border-0" id="modal-btn">
    <div class="card-header p-1 rounded-0 d-flex justify-content-between">
      <div class="d-flex p-0">
        <div class="d-flex mx-1 align-self-center">
          <%= image_tag article.author.image.url, class: 'rounded', :size => '30x30' if article.author.image.url.present? %>
        </div>
        <div class="d-flex flex-column align-self-center" id="date">
          <div class="mr-1 font-weight-bold text-left" id="author">
            <%= article.author.username %>
            <%= render 'users/user_card_attribute_badge', user: article.author %>
          </div>
          <div class="text-truncate" id="date"><%= article.created_at.strftime("%m月%d日 %H:%M") %></div>
        </div>
      </div>
    </div>
  </button>
  <%= render 'articles/articles_cards_card_modal_user', article: article, user: article.user, user_type: user_type %>
  <button type="button" data-toggle="modal" data-target="#article-modal-<%= article_type %>-<%= article.id %>" class="m-0 p-0 border-0" id="modal-btn">
    <div class="card-header rounded-0 p-1 px-2 btn-secondary text-align-start" data-toggle="modal" data-target="#article-modal">
      <div class="align-self-center text-truncate text-left" id="title">
        <%= render 'articles/article_card_notice_type_badge', article: article %>
        <%= article.title %>
      </div>
    </div>
    <div class="card d-flex m-0 p-0 justify-content-center">
      <div class="articles-cards-picture-field">
        <%= image_tag article.article_picture.url, class: "article-picture" if article.article_picture.url.present? %>
      </div>
    </div>
    <div class="card-body p-2 text-left" id="article-body">
      <%= markdown(article.body).html_safe %>
    </div>
    <div class="card-footer p-0" id="counts">
      コメント(<%= article.comment_count %>) いいね(<%= article.like_count %>)
    </div>
  </button>
  <%= render 'articles/articles_cards_card_modal_article', article: article, article_type: article_type %>
  <div class="card-footer p-0" id="tag-footer">
    <%# <%= render 'tags/tags_badges_line', article: article, tags: article.tag_list %> %>
  </div>
</div>

app/views/articles/_articles_cards_card_modal_article.html.erb
<div class="modal fade article-modal" id="article-modal-<%= article_type %>-<%= article.id %>" tabindex="-1" role="dialog" aria-labelledby="記事プレビュー" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <%= link_to article.user do %>
        <div class="modal-header p-1 d-flex justify-content-between border-secondary" id="author">
          <div class="d-flex p-0">
            <div class="d-flex mx-1 align-self-center">
              <%= image_tag article.author.image.url, class: 'rounded', :size => '30x30' if article.author.image.url.present? %>
            </div>
            <div class="d-flex flex-column align-self-center" id="date">
              <div class="mr-1 font-weight-bold text-left" id="author">
                <%= article.author.username %>
                <%= render 'users/user_card_attribute_badge', user: article.author %>
              </div>
              <div class="text-truncate" id="date"><%= article.created_at.strftime("%m月%d日 %H:%M") %></div>
            </div>
          </div>
          <div class="align-self-center">
            <%= link_to "記事詳細へ", article, class: "p-1 btn btn-sm btn-primary" %>
            <button type="button" class="p-1 btn btn-sm btn-secondary" data-dismiss="modal">閉じる</button>
          </div>
        </div>
      <% end %>
      <%= link_to article do %>
        <div class="modal-header border-secondary rounded-0 p-1 pl-2" id="title">
          <div>
            <%= render 'articles/article_card_notice_type_badge', article: article %>
            <%= article.title %>
          </div>
        </div>
      <% end %>
      <div class="modal-header rounded-0 p-0 pl-2">
        <%# <%= render 'tags/tags_badges_line', article: article, tags: article.tag_list %> %>
      </div>
      <div class=" d-flex p-0 justify-content-center">
        <div class="card m-2 border-0 rounded-0 article-modal-picture-field">
          <%= image_tag article.article_picture.url, class: "article-picture" if article.article_picture.url.present? %>
        </div>
      </div>
      <div class="modal-body p-2 px-3 overflow-auto">
        <%= markdown(article.body).html_safe %>
      </div>
      <div class="modal-footer border-top-0 p-2">
        <%= link_to "記事詳細へ", article, class: "p-1 btn btn-sm btn-primary" %>
        <button type="button" class="p-1 btn btn-sm btn-secondary" data-dismiss="modal">閉じる</button>
      </div>
      <div class="py-3 border-top comments-list" id="comments-list-<%= article.id %>" >
        <%= render 'comments/comments_list', comments: article.comments %>
      </div>
      <div id="comment-poster">
        <%= render 'comments/comment_form_post', article: article %>
      </div>
    </div>
  </div>
</div>

app/views/articles/_articles_cards_card_modal_user.html.erb
<div class="modal fade user-modal" id="user-modal-<%= user_type %>-<%= article.user.id %>" tabindex="-1" role="dialog" aria-labelledby="記事プレビュー" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document" id="user-modal-dialog">
    <div class="modal-content">
      <%= render 'users/user_card', user: user %>
    </div>
  </div>
</div>

app/views/articles/_new_or_edit_form_for_article.html.erb
<div class="mx-auto" id="article-form">
  <%= form_for @article do |f| %>
    <div class= "input-group" id="article-title">
      <span :title, class="input-group-text">タイトル</span>
      <%= f.text_field :title, class: 'form-control', placeholder: "タイトルを記載" %>
    </div>
    <div class="card mb-2" id="article-body">
      <div class="card-header py-1">
        <ul class="nav nav-pills card-header-pills">
          <li class="nav-item">
            <a class="nav-link active py-1 mr-2" id="editor-tab" data-toggle="tab" href="#editor-area" role="tab" aria-controls="editor" aria-selected="true">記述</a>
          </li>
          <li class="nav-item">
            <a class="nav-link p-1" id="preview-tab" data-toggle="tab" href="#preview-area" role="tab" aria-controls="preview" aria-selected="false">プレビュー</a>
          </li>
        </ul>
      </div>
      <div class="card-body" id="markdown-editor">
        <div class="tab-content" >
          <div class="tab-pane show active border" id="editor-area" role="tabpanel" aria-labelledby="editor-tab">
            <%= f.text_area :body, class: 'form-control', id: 'editor', "v-model" => "input", name: "article[body]", placeholder: "本文を記載" %>
          </div>
          <div class="tab-pane border" id="preview-area" role="tabpanel" aria-labelledby="preview-tab" >
            <div id="preview-area" class="content" v-html='input | marked'></div>
          </div>
        </div>
      </div>
    </div>
    <div class="mb-2 badge badge-light field">
      <% if current_page?(controller: 'articles', action: 'new') %>
      <% elsif current_page?(controller: 'articles', action: 'edit') %>
        <%= image_tag @article.article_picture.url if @article.article_picture.url.present? %>
      <% end %>
      <%= f.file_field :article_picture, class: "m-0" %>
    </div>
    <% if current_page?(controller: 'articles', action: 'new') %>
    <% elsif current_page?(controller: 'articles', action: 'edit') %>
      <div class="badge badge-primary mb-2"><%= f.check_box :remove_article_picture %>画像を削除する</div>
    <% end %>
    <div class= "input-group" id="article-tags">
      <span :tag_list, class="input-group-text px-4">タグ</span>
      <%= f.text_field :tag_list, value: @article.tag_list.join(","), class: 'form-control', placeholder: "タグを追加(複数可)" %>
    </div>
    <% if current_user.admin_flg == true %>
      <div class="badge badge-lg badge-danger mb-2"><%= f.check_box :update_note, value: 'true' %>アップデートのお知らせ</div>
    <% end %>
    <div class="mb-3">
      <% if current_page?(new_article_path) %>
        <%= f.submit '上記の内容で投稿する', class: 'btn btn-secondary btn-lg btn-block' %>
      <% else %>
        <%= f.submit '編集を登録する', class: 'btn btn-secondary btn-lg btn-block' %>
      <% end %>
    </div>
  <% end %>
</div>

<script type="text/javascript">
window.onload = function() {
  new Vue({
    el: '#markdown-editor',
    data: {
      input: '<%= j @article.body %>',
    },
    filters: {
      marked: marked,
    }
  });
};
</script>

app/views/articles/edit.html.erb
<% provide(:title, '記事の編集') %>
<%= render 'articles/new_or_edit_form_for_article' %>

app/views/articles/index.html.erb
<% provide(:title, '新着記事一覧') %>
<meta name="turbolinks-cache-control" content="no-cache">
<%= render 'articles/articles_cards', articles: @articles, user_type: 'index', article_type: 'index' %>

app/views/articles/new.html.erb
<% provide(:title, '新規記事の投稿') %>
<%= render 'articles/new_or_edit_form_for_article' %>

app/views/articles/show.html.erb
<% provide(:title, "記事詳細") %>

<div class="col-11 mx-auto">
  <%= render 'articles/article_card', article: @article, like: @like %>
  <div class="comments-list p-2" id="comments-list-<%= @article.id %>" >
    <%= render 'comments/comments_list', comments: @article.comments %>
  </div>
  <div id="comment-poster">
    <%= render 'comments/comment_form_post', article: @article %>
  </div>
</div>