config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'users/index'
  get 'users/show'
  root 'articles#index'
  get 'home' => 'articles#index'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  post 'tags/:id/edit' => 'tags#edit'

  resources :users, only: %i[index show]

  resources :tags

  resources :users do
    member do
      get :following, :followers
    end
    resources :relationships, only: %i[create destroy]
  end

  resources :articles do
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.page(params[:page]).per(8).order(name: :asc)
  end

  def show
    @tag = ActsAsTaggableOn::Tag.all.find(params[:id])
  end

  def edit
    @tag = ActsAsTaggableOn::Tag.all.find(params[:id])
  end

  def update
    @tag = ActsAsTaggableOn::Tag.all.find(params[:id])
    @tag.assign_attributes(tag_params)
    if @tag.save
      redirect_to tag_path(params[:id]), notice: 'タグの情報を更新しました！'
    else
      render 'edit'
    end
  end

  def destroy
    @tag = ActsAsTaggableOn::Tag.all.find(params[:id])
    @tag.destroy
    redirect_to controller: 'tags', action: 'index'
  end

  private

  def tag_params
    params.require(:tag).permit(:description)
  end
end

app/helpers/tags_helper.rb
# frozen_string_literal: true

module TagsHelper
end

app/views/tags/_tag_badge.html.erb
<div class="d-flex text-truncate">
  <% tags.each do |tag| %>
    <div class="tag badge badge-primary m-1 align-self-center"><%= tag %></div>
  <% end %>
</div>

app/views/tags/_tags_badges_line.html.erb
<div class="tags d-flex p-1">
  <% if tags.present? %>
    <% tags.each do |tag| %>
      <div class="mr-1">
        <%= link_to tag_path(id = ActsAsTaggableOn::Tag.find_by(name: tag).id) do %>
          <div class="tag badge badge-primary"><%= tag %></div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="tag badge badge-secondary px-3 align-self-center">タグ登録なし</div>
  <% end %>
</div>

app/views/tags/edit.html.erb
<% provide(:title, "#{@tag.name}の説明文を編集") %>

<div class="col-11 mx-auto">
  <%= form_for @tag, url: url_for(:controller => :tags, :action => :update) do |f| %>
    <div class="card mb-2" id="article-body">
      <div class="card-header py-1">
        <ul class="nav nav-pills card-header-pills">
          <li class="nav-item">
            <a class="nav-link active py-1 mr-2" id="editor-tab" data-toggle="tab" href="#editor-area" role="tab" aria-controls="editor" aria-selected="true">記述</a>
          </li>
          <li class="nav-item">
            <a class="nav-link p-1" id="preview-tab" data-toggle="tab" href="#preview-area" role="tab" aria-controls="preview" aria-selected="false">プレビュー</a>
          </li>
        </ul>
      </div>
      <div class="card-body" id="markdown-editor">
        <div class="tab-content" >
          <div class="tab-pane show active border" id="editor-area" role="tabpanel" aria-labelledby="editor-tab">
            <%= f.text_area :description, class: 'form-control', id: 'editor', "v-model" => "input", name: "tag[description]", placeholder: "タグの説明を記載" %>
          </div>
          <div class="tab-pane border" id="preview-area" role="tabpanel" aria-labelledby="preview-tab" >
            <div id="preview-area" class="content" v-html='input | marked'></div>
          </div>
        </div>
      </div>
    </div>
    <%= f.submit '編集を登録する', class: 'btn btn-secondary btn-lg btn-block' %>
  <% end %>
</div>

<script type="text/javascript">
window.onload = function() {
  new Vue({
    el: '#markdown-editor',
    data: {
      input: '<%= j @tag.description %>',
    },
    filters: {
      marked: marked,
    }
  });
};
</script>

app/views/tags/index.html.erb
<% provide(:title, "カテゴリタグ一覧") %>

<div class="row col-11 mx-auto">
  <% @tags.each do |tag| %>
    <div class="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-3 p-0">
      <div type="button" class="mr-3 mb-3" data-toggle="modal" data-target="#tag-index-modal-<%= tag.id %>">
        <div class="tag-index-card d-flex card p-0 rounded-0">
          <div class="card-header py-1 d-flex">
            <%= tag.name %>
          </div>
          <div class="card-body py-1 px-2">
            <% if tag.description.present? %>
              <%= markdown(tag.description).html_safe %>
            <% else %>
              <div style="color: gray;">
                まだ説明文がありません。
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="tag-index-modal modal fade" id="tag-index-modal-<%= tag.id %>" tabindex="-1"
          role="dialog" aria-labelledby="label1" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content rounded-0 border-0">
          <div class="modal-header p-2 d-flex justify-content-between">
            <h5 class="modal-title" id="label1"><%= tag.name %></h5>
            <div>
              <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">閉じる</button>
              <%= link_to tag_path(tag.id) do %>
                <button type="button" class="btn btn-sm btn-primary">タグの詳細へ</button>
              <% end %>
            </div>
          </div>
          <div class="modal-body">
            <% if tag.description.present? %>
              <%= markdown(tag.description).html_safe %>
            <% else %>
              <div style="color: gray;">
                まだ説明文がありません。
              </div>
            <% end %>
          </div>
          <div class="modal-footer p-1">
            <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">閉じる</button>
            <%= link_to tag_path(tag.id) do %>
              <button type="button" class="btn btn-sm btn-primary">タグの詳細へ</button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="container d-flex">
    <div class="mx-auto">
      <%= paginate @tags.page(params[:page]).per(8).order(name: :asc) %>
    </div>
  </div>
</div>

app/views/tags/show.html.erb
<% provide(:title, "#{@tag.name}とは？") %>

<div class="col-11 mx-auto">
  <div class="card" id="tag-card">
    <div class="card-header d-flex justify-content-between">
      <div class="d-flex align-self-center">
        <%= @tag.name %>
      </div>
      <div>
        <% if user_signed_in? %>
          <%= link_to "説明の編集", edit_tag_path, method: :get, class: 'float-left btn btn-sm btn-light' ,id: 'edit-btn' %>
          <% if current_user.admin_flg == true %>
            <%= link_to "タグの削除", tag_path(@tag), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'float-left ml-2 btn btn-sm btn-light', id: 'delete-btn' %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="card-body">
      <% if @tag.description.present? %>
        <%= markdown(@tag.description).html_safe %>
      <% else %>
      <div style="color: gray;">
        まだ説明文がありません。
      </div>
      <% end %>
    </div>
  </div>

  <% if Article.tagged_with(@tag.name).present? %>
    <h4 class="title-sentence"><%= @tag.name %>のタグがついた記事</h4>
  <% else %>
    <h4 class="title-sentence"><%= @tag.name %>のタグがついた記事があれば以下に一覧表示されます。</h4>
  <% end %>
</div>

<%= render 'articles/articles_cards',
 articles: Article.tagged_with(@tag.name).order(created_at: :desc),
 user_type: 'index', article_type: 'index' %>