config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'users/index'
  get 'users/show'
  root 'articles#index'
  get 'home' => 'articles#index'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  post 'tags/:id/edit' => 'tags#edit'

  resources :users, only: %i[index show]

  resources :tags

  resources :users do
    member do
      get :following, :followers
    end
    resources :relationships, only: %i[create destroy]
  end

  resources :articles do
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end
end

app/views/layouts/_header.html.erb
<header id="header-content">
  <div class="container-fruid">
    <nav class="navbar header-menu d-flex">
      <ul class="navbar-nav  navbar-expand">
        <li class="nav-item"><a class="navbar-brand" href="/home">ホーム</a></li>
        <li class="nav-item"><a class="navbar-brand" href="/users">アカウント一覧</a></li>
        <li class="nav-item"><a class="navbar-brand" href="/tags">タグ一覧</a></li>
        <li class="nav-item align-self-center">
          <form class="form-inline">
          <% if user_signed_in? %>
            <%= link_to '新規記事作成', new_article_url,
                class: 'btn btn-sm btn-dark btn-block navbar-text p-1' %>
          <% end %>
          </form>
        </li>
      </ul>
      <%= render 'layouts/readme_btn' %>
      <% if user_signed_in? %>
        <div class="dropdown">
          <button class="btn btn-sm btn-dark dropdown-toggle" type="button"
            id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag current_user.image.url, class: 'rounded', :size => '15x15' if current_user.image.url.present? %>
            <%= current_user.username %> さん
            <%= render 'users/user_card_attribute_badge', user: current_user %>
          </button>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <button class="dropdown-item" type="button"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></button>
            <button class="dropdown-item" type="button"><%= link_to 'ユーザー設定変更', edit_user_registration_path %></button>
            <button class="dropdown-item" type="button"><%= link_to 'ユーザー詳細', current_user %></button>
            <% if current_user.try(:admin_flg?) %>
              <button class="dropdown-item" type="button"><%= link_to '管理者ツール画面', rails_admin_path %></button>
            <% end %>
          </div>
        </div>
      <% else %>
        <%= link_to 'ログイン', new_user_session_path,
          class: 'col-2 float-right btn btn-sm btn-primary btn-block' %>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/_readme_btn.html.erb
<button type="button" data-toggle="modal" data-backdrop="false"
 data-target="#readme-modal" class="p-1 col-auto navbar-brand
  btn btn-sm btn-warning align-self-center" id="readme-btn">
  アプリ概要(README.md)
</button>
<%= render 'layouts/readme_btn_modal' %>

app/views/layouts/_readme_btn_modal.html.erb
<div class="modal fade" id="readme-modal" tabindex="-1" role="dialog"
 aria-labelledby="READMEプレビュー" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header p-1 border-secondary">
          <button type="button" class="btn btn-secondary btn-block"
           data-dismiss="modal">閉じる</button>
        </div>
        <div class="modal-header github-grass d-flex justify-content-center">
          <a href="https://github.com/RiSEblackbird" target="_blank">
            <img class="grass-image" src="https://grass-graph.moshimo.works/images/RiSEblackbird.png?">
          </a>
        </div>
      <div class="modal-body p-2 px-3 overflow-auto">
        <%= markdown(p File.open("./README.md").read).html_safe %>
      </div>
      <div class="modal-footer border-top-0 p-2">
        <button type="button" class="p-1 btn btn-secondary btn-block"
         data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="sidebar mx-3">
  <% @articles = Article.update_notice.by_dates.sidebar_limit %>
  <div class="card rounded-0 mb-4" id="sidebar-card">
    <div class="card-header rounded-0 p-1">最新アップデート</div>
      <div class="card-body p-1">
        <% @articles.each do |article| %>
          <%= link_to article do %>
            <div class="row d-flex mx-auto justify-content-between">
              <div class="px-0 col-6 col-lg-7 col-xl-8 d-flex ">
                <div class="text-truncate"><%= article.title %></div>
              </div>
              <div class="d-flex">
                --<%= article.created_at.strftime("%m/%d") %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
  </div>
  <% @articles = Article.by_dates.sidebar_limit %>
  <div class="card rounded-0 mb-4" id="sidebar-card">
    <div class="card-header rounded-0 p-1">投稿日順</div>
      <div class="card-body p-1">
        <% @articles.each do |article| %>
          <%= link_to article do %>
            <div class="row d-flex mx-auto justify-content-between">
              <div class="px-0 col-6 col-lg-7 col-xl-8 d-flex ">
                <div class="text-truncate"><%= article.title %></div>
              </div>
              <div class="d-flex">
                --<%= article.created_at.strftime("%m/%d") %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
  </div>
  <% @articles = Article.by_comments.sidebar_limit %>
  <div class="card rounded-0 mb-4" id="sidebar-card">
    <div class="card-header rounded-0 p-1">コメント数順</div>
      <div class="card-body p-1">
        <% @articles.each do |article| %>
          <%= link_to article do %>
            <div class="row d-flex mx-auto justify-content-between">
              <div class="px-0 col-6 col-lg-7 col-xl-8 d-flex ">
                <div class="text-truncate"><%= article.title %></div>
              </div>
              <div class="d-flex">
                --(<%= article.comment_count %>)
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
  </div>
  <% @tags = ActsAsTaggableOn::Tag.most_used(10).order(taggings_count: :desc) %>
  <div class="card rounded-0 mb-4" id="sidebar-card">
    <div class="card-header rounded-0 p-1">人気タグ</div>
      <div class="card-body p-1">
        <% @tags.each do |tag| %>
          <%= link_to tag_path(tag.id) do %>
            <div class="row d-flex mx-auto justify-content-between">
              <div class="px-0 col-6 col-lg-7 col-xl-8 d-flex ">
                <div class="text-truncate"><%= tag.name %></div>
              </div>
              <div class="d-flex">
                --(<%= tag.taggings_count %>)
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!マークダウンプレビュー用のスクリプト>
<script src='https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.10/vue.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.js'></script>
<html>
  <head>
    <title><%= (yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    <%= analytics_init if GoogleAnalytics.valid_tracker? %>

    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@RiSE_blackbird">
    <meta property="og:url" content="https://peaceful-reaches-94880.herokuapp.com">
    <meta property="og:title" content="BlogApp2019_Railsポートフォリオ">
    <meta property="og:description" content="Ruby_on_Railsによるブログアプリです。記事投稿や画像アップ機能、コメント投稿機能などを備えています。">
    <meta property="og:image" content="OGP.JPG">
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="main-back-color"></div>
    <div class="main-back-img"></div>

    <div class="row" id="main-layout">
      <div id="login-alert">
        <% if notice %>
          <div class="alert alert-info alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
              <span class="sr-only">close</span>
            </button>
            <%= notice %>
          </div>
        <% end %>
        <% if alert %>
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
              <span class="sr-only">close</span>
            </button>
            <%= alert %>
          </div>
        <% end %>
      </div>
      <div class="col-12 col-lg-10" id="cards-space">
        <div class="title-sentence">
          <h4><%= (yield(:title)) %></h4>
        </div>
        <%= yield %>
      </div>
      <div class="col-lg-2 justify-self-center mx-auto px-1"><%= render 'layouts/sidebar' %></div>
    </div>
  </body>
</html>